apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-readonly-config
  namespace: mcp-registry
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        
        upstream registry {
            server 127.0.0.1:8080;
        }
        
        server {
            listen 80;
            server_name _;
            
            location /v0/health {
                if ($request_method !~ ^(GET|HEAD|OPTIONS)$ ) {
                    return 405;
                }
                proxy_pass http://registry;
                proxy_set_header Host $host;
            }
            
            location ~ ^/v0/servers {
                if ($request_method !~ ^(GET|HEAD|OPTIONS)$ ) {
                    return 405;
                }
                proxy_pass http://registry;
                proxy_set_header Host $host;
            }
            
            location ~ ^/v0/(publish|auth) {
                return 403;
            }
            
            location / {
                return 404;
            }
        }
    }