# Kind cluster configuration for MCP Registry deployment
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mcp-registry
nodes:
- role: control-plane
  image: kindest/node:v1.31.0
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 9080
    protocol: TCP
  - containerPort: 443
    hostPort: 9443
    protocol: TCP
- role: worker
  image: kindest/node:v1.31.0
- role: worker
  image: kindest/node:v1.31.0